# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Publish Artifact'
  steps:
  - script: |
      mkdir -p build
      make
    displayName: 'Build'
  

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(System.DefaultWorkingDirectory)/build/SourceCodeBuild.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - script: |
     echo "Publishing Universal Package"
     ls $(System.DefaultWorkingDirectory)/build
    displayName: 'List Build Directory Contents'


