name: Build Artifacts

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: |
        cd SysCtrl
        make

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SysCtrl-artifacts
        path: SysCtrl/build

    - name: Create develop branch if it doesn't exist
      run: |
        git fetch origin
        git checkout -B develop origin/develop || git checkout -b develop

    - name: Store artifacts in develop branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by default by GitHub Actions
      run: |
        git config --local user.email "mohitkumar.sahu@tatatechnologies.com"
        git config --local user.name "mss924043"
        if [ ! -d "artifacts" ]; then
        mkdir artifacts
        fi
        cp -r SysCtrl/build/* artifacts/
        git add .
        git commit -m "Publish artifacts"
        git push origin develop

  upload_to_onedrive:
    name: Upload Artifacts to OneDrive
    runs-on: ubuntu-latest
    needs: [build]  # This ensures this job runs after the 'build' job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up rclone
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install rclone
      run: |
        python -m pip install --upgrade pip
        pip install rclone

    - name: Upload artifacts to OneDrive
      run: |
        rclone copy SysCtrl/build "onedrive:tatatechnologies-my.sharepoint.com/personal/mss924043_tatatechnologies_com/Documents/Documents/Github_TTL/Binaries" --progress --create-empty-src-dirs
