name: Build Artifacts

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: |
        cd SysCtrl
        make

    - name: Download artifacts
      run: |
        curl -L -o SysCtrl-artifacts.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/mss924043/SourceCodeBuild/actions/artifacts/
        ls -l SysCtrl-artifacts.zip  # Check if the file exists and its size
        unzip -l SysCtrl-artifacts.zip  # List the contents of the ZIP file

    - name: Create artifacts directory
      run: |
        mkdir -p artifacts
        mv SysCtrl-artifacts.zip artifacts/

    - name: Publish artifacts to master repo
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add artifacts/
        git commit -m "Add SysCtrl artifacts"
        git push origin master
