name: Build Artifacts

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: |
        cd SysCtrl
        make

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SysCtrl-artifacts
        path: SysCtrl/build

    - name: Download artifacts
      run: |
        response=$(curl -s -w "%{http_code}" -o artifacts.zip https://api.github.com/repos/mss924043/SourceCodeBuild/actions/artifacts/1241268954/zip)
        if [ "$response" == "200" ]; then
          echo "Artifacts downloaded successfully."
          mv artifacts.zip "/mnt/c/Users/mss924043/OneDrive - Tata Technologies/Documents/Github_TTL"
        else
          echo "Error: Artifacts not found."
        fi
