name: Build Artifacts and Upload to SharePoint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: |
        cd SysCtrl
        make

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SysCtrl-artifacts
        path: SysCtrl/build

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone with OneDrive
      run: |
        echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
      env:
        RCLONE_CONFIG: |
          [onedrive]
          type = onedrive
          token = {"access_token":"YOUR_ACCESS_TOKEN","expiry":"2024-02-15T18:49:12.517785983Z"}
          drive_id = YOUR_DRIVE_ID
          drive_type = personal
        ONE_DRIVE_ACCOUNT: ${{ secrets.ONE_DRIVE_ACCOUNT }}
        ONE_DRIVE_PASSWORD: ${{ secrets.ONE_DRIVE_PASSWORD }}

    - name: Upload to OneDrive using rclone
      run: |
        rclone copy SysCtrl/build "onedrive:tatatechnologies-my.sharepoint.com/personal/mss924043_tatatechnologies_com/Documents/Documents/Github_TTL/Binaries" --progress --create-empty-src-dirs --config ~/.config/rclone/rclone.conf
