name: Build Artifacts

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: cd SysCtrl && make build_artifacts
