name: Build Artifacts and Upload to SharePoint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: |
        cd SysCtrl
        make

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SysCtrl-artifacts
        path: SysCtrl/build

    - name: Download artifacts from develop branch
      uses: actions/download-artifact@v2
      with:
        name: SysCtrl-artifacts
        path: downloaded_artifacts

    - name: Install SharePoint Uploader
      run: |
        sudo npm install -g spsave

    - name: Upload to SharePoint
      run: |
        spsave -s https://tatatechnologies-my.sharepoint.com/personal/mss924043_tatatechnologies_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmss924043%5Ftatatechnologies%5Fcom%2FDocuments%2FDocuments%2FGithub%5FTTL%2FBinaries&view=0 -f downloaded_artifacts/* -U mohitkumar.sahu@tatatechnologies.com
