name: Build Artifacts

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up build environment
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build artifacts
      run: |
        cd SysCtrl
        make

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SysCtrl-artifacts
        path: SysCtrl/build

    - name: Store artifacts in master branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        mkdir artifacts
        cp -r SysCtrl/build/* artifacts/
        git add .
        git commit -m "Publish artifacts"
        git push
