name: Build Artifacts and Push to Local Machine

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build artifacts
        run: |
          cd SysCtrl
          make

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SysCtrl-artifacts
          path: SysCtrl/build

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: SysCtrl-artifacts
          path: SysCtrl-artifacts/D:\Binaries

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.LOCAL_MACHINE_SSH_KEY }} ${{ secrets.LOCAL_MACHINE_USERNAME }}@${{ secrets.LOCAL_MACHINE_HOST }} -p ${{ secrets.LOCAL_MACHINE_PORT }} echo "SSH connection successful"

      - name: Push artifacts to local machine
        if: github.ref == 'refs/heads/develop'  # Only push from develop branch
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LOCAL_MACHINE_HOST }}
          username: ${{ secrets.LOCAL_MACHINE_USERNAME }}
          key: ${{ secrets.LOCAL_MACHINE_SSH_KEY }}
          port: ${{ secrets.LOCAL_MACHINE_PORT }}
          source: SysCtrl-artifacts
          target: D:\Binaries
